services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: emt
      POSTGRES_PASSWORD: emt
      POSTGRES_DB: book_shop
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./02-views.sql:/docker-entrypoint-initdb.d/02-views.sql
    ports:
      - "2345:5432"
volumes:
  postgres_data: